name: Deploy to Hostinger (lftp)

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        working-directory: sleepy-spiral
        run: npm ci

      - name: Build project
        working-directory: sleepy-spiral
        run: npm run build

      - name: Verify FTP Secret
        env:
          FTP_PASSWORD: ${{ secrets.HOSTINGER_FTP_PASSWORD }}
        run: |
          if [ -z "$FTP_PASSWORD" ] || [ "$FTP_PASSWORD" = "" ]; then
            echo "❌ HOSTINGER_FTP_PASSWORD belum diset di Secrets."
            exit 1
          fi
          echo "✅ FTP password tersedia."

      - name: Install lftp
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp

      - name: Deploy via lftp mirror
        env:
          FTP_PASSWORD: ${{ secrets.HOSTINGER_FTP_PASSWORD }}
        run: |
          echo "📤 Deploying with lftp mirror..."
          lftp -e "
            set ftp:passive-mode on;
            set net:max-retries 2;
            set net:timeout 30;
            open -u u230709022,$FTP_PASSWORD 145.79.14.23;
            lcd sleepy-spiral/dist;
            cls -l;
            pwd;
            cd /public_html;
            mirror -R --delete -e -p -v . .;
            bye
          "
          echo "✅ Deployment selesai."

      - name: Verify deployment
        run: |
          echo "🌐 Website should be live at: https://berkahcakrasolusindo.com"
